// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DeleteConfirmController from "./delete_confirm_controller"
application.register("delete-confirm", DeleteConfirmController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FadeOutController from "./fade_out_controller"
application.register("fade-out", FadeOutController)

import MenuFilterController from "./menu_filter_controller"
application.register("menu-filter", MenuFilterController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import UserModalController from "./user_modal_controller"
application.register("user-modal", UserModalController)

import UserProfileController from "./user_profile_controller"
application.register("user-profile", UserProfileController)

import UsersController from "./users_controller"
application.register("users", UsersController)
