// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DeleteConfirmController from "./delete_confirm_controller"
application.register("delete-confirm", DeleteConfirmController)

import FadeOutController from "./fade_out_controller"
application.register("fade-out", FadeOutController)

import MenuFilterController from "./menu_filter_controller"
application.register("menu-filter", MenuFilterController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import UsersController from "./users_controller"
application.register("users", UsersController)
